---
abstract: 'Scrape f1.com for next race en championship.'
author:
  - 'Freek Kalter <freek@kalteronline.org>'
build_requires:
  FindBin: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Scraper-F1
requires:
  Data::Dumper: 0
  DateTime::Format::Duration: 0
  DateTime::Format::Natural: 0
  Exporter: 0
  HTML::TreeBuilder: 0
  LWP: 0
  Storable: 0
  Time::Piece: 0
  parent: 0
  perl: v5.14.0
  strict: 0
  warnings: 0
version: 0.003
